"""Regenerate every reported number from results/runs.csv (preregistered plan, Section 6).

Works at each reporting gate with whatever arms are complete:
  Arm A only        -> seed SD per task with bootstrap interval
  Arms A + B        -> B variance components (MoM + REML), headline ratio R with interval,
                       tier permutation test, disagreement flags, boundary flags, power
  Arms A + B + C    -> C components, D = s2_p(B) - s2_p(C) with interval, Holm across the
                       primary family (3 tasks x {R > 1, D > 0}) and secondary family (tier)

Outputs: results/analysis.json and results/analysis_summary.md
Usage:   python analysis/run_analysis.py [--runs results/runs.csv] [--n_boot 2000] [--seed 0]
"""
import argparse, json, os, sys
import numpy as np
import pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vc

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TASKS = ["lift", "can", "square"]
OPS = ["better_operator_1", "better_operator_2", "okay_operator_1",
       "okay_operator_2", "worse_operator_1", "worse_operator_2"]
TIER_OF = {op: op.split("_")[0] for op in OPS}


def table(df, arm, task, keys, seeds):
    """(P, S) table of success rates; None if any cell missing."""
    sub = df[(df.arm == arm) & (df.task == task)]
    T = np.full((len(keys), len(seeds)), np.nan)
    for i, k in enumerate(keys):
        for j, s in enumerate(seeds):
            r = sub[(sub.partition_key == k) & (sub.seed == s)]
            if len(r) == 1:
                T[i, j] = float(r.success_rate.iloc[0])
    return None if np.isnan(T).any() else T


def clean(d):
    """Make JSON-serialisable and drop bootstrap draws."""
    out = {}
    for k, v in d.items():
        if k == "draws":
            continue
        if isinstance(v, (np.floating, float)):
            out[k] = None if not np.isfinite(v) else float(v)
        elif isinstance(v, (np.integer,)):
            out[k] = int(v)
        elif isinstance(v, (np.bool_, bool)):
            out[k] = bool(v)
        else:
            out[k] = v
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default=os.path.join(REPO, "results", "runs.csv"))
    ap.add_argument("--n_boot", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n_power_sim", type=int, default=200)
    a = ap.parse_args()
    df = pd.read_csv(a.runs)
    df["seed"] = df["seed"].astype(int)
    rng = np.random.default_rng(a.seed)
    B_keys = [f"B_drop_{op}" for op in OPS]
    C_keys = [f"C_rand_{i}" for i in range(1, 7)]
    tiers = [TIER_OF[op] for op in OPS]

    R = {"n_boot": a.n_boot, "bootstrap_seed": a.seed, "tasks": {}}
    lines = ["# Analysis summary (auto-generated by analysis/run_analysis.py)", ""]
    prim_p, prim_labels, sec_p, sec_labels = [], [], [], []

    for task in TASKS:
        T = {"arms_available": []}
        # ---- Arm A
        A = df[(df.arm == "A") & (df.task == task)].sort_values("seed")
        if len(A) == 10:
            vec = A.success_rate.to_numpy(float)
            bs = vc.bootstrap_seed_sd(vec, a.n_boot, rng)
            # Descriptive (limitation 7): binomial SD of a single 50-rollout success estimate at the mean
            # rate, and the seed SD after subtracting that noise floor in quadrature (not used in tests).
            pbar = float(vec.mean()); n_roll = int(A.n_rollouts.iloc[0])
            binom_sd = float(np.sqrt(pbar * (1 - pbar) / n_roll))
            sd_raw = vc.seed_sd(vec)
            T["A"] = {"success_rates": vec.tolist(), "mean": pbar, "sd_seed": sd_raw,
                      "sd_seed_ci": [float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5))],
                      "min": float(vec.min()), "max": float(vec.max()),
                      "binomial_sd_50_rollouts": binom_sd,
                      "sd_seed_minus_binomial": float(np.sqrt(max(sd_raw ** 2 - binom_sd ** 2, 0.0)))}
            T["arms_available"].append("A")
        elif len(A):
            T["A_partial"] = {"n_done": int(len(A)), "success_rates": A.success_rate.tolist()}
        # ---- Arm B
        Bt = table(df, "B", task, B_keys, [1, 2, 3])
        if Bt is not None:
            mom, reml = vc.mom_two_way(Bt), vc.reml_two_way(Bt)
            rowm = Bt.mean(axis=1)
            T["B"] = {"table": Bt.tolist(), "row_keys": B_keys, "seeds": [1, 2, 3],
                      "partition_means": dict(zip(OPS, rowm.tolist())),
                      "mom": clean(mom), "reml": clean(reml), "f_test": vc.f_test_p(Bt),
                      "disagree": vc.estimators_disagree(mom, reml),
                      "within_table_ratio": float(vc.within_table_ratio(Bt)),
                      "tier_permutation": vc.tier_permutation_test(rowm, tiers),
                      "tier_pairwise": vc.pairwise_tier_spread(rowm, tiers),
                      "min_detectable_sd_p_alpha05": vc.min_detectable_sd_p(mom["s2_e"]),
                      }
            T["arms_available"].append("B")
            if "A" in T:
                rr = vc.bootstrap_ratio(Bt, np.array(T["A"]["success_rates"]), a.n_boot, rng, "mom")
                T["headline_ratio_mom"] = clean(rr)
                rr2 = vc.bootstrap_ratio(Bt, np.array(T["A"]["success_rates"]), min(a.n_boot, 500), rng, "reml")
                T["headline_ratio_reml"] = clean(rr2)
                prim_p.append(rr["p_R_le_1"]); prim_labels.append(f"{task}:R>1")
                # Amendment 1(b): power of the actual headline procedure under fitted nuisance SDs
                sdA = T["A"]["sd_seed"]
                grid = [round(sdA * f, 4) for f in (1.0, 1.5, 2.0, 3.0, 4.0)] if sdA > 0 else []
                T["power_headline_procedure"] = vc.power_ratio_sim(
                    sdA, mom["sd_e"], mom["sd_s"], grid, n_sim=a.n_power_sim, n_boot=300, rng=rng) if grid else {}
            sec_p.append(T["B"]["tier_permutation"]["p_value"]); sec_labels.append(f"{task}:tier")
        # ---- Arm C
        Ct = table(df, "C", task, C_keys, [1, 2, 3])
        if Ct is not None:
            momc, remlc = vc.mom_two_way(Ct), vc.reml_two_way(Ct)
            T["C"] = {"table": Ct.tolist(), "row_keys": C_keys, "seeds": [1, 2, 3],
                      "mom": clean(momc), "reml": clean(remlc), "f_test": vc.f_test_p(Ct),
                      "disagree": vc.estimators_disagree(momc, remlc)}
            T["arms_available"].append("C")
            if Bt is not None:
                dd = vc.bootstrap_diff(Bt, Ct, a.n_boot, rng)
                T["B_minus_C"] = clean(dd)
                prim_p.append(dd["p_D_le_0"]); prim_labels.append(f"{task}:D>0")
        R["tasks"][task] = T

    # ---- Holm within families
    if prim_p:
        adj = vc.holm(prim_p)
        R["primary_family"] = [{"contrast": l, "p_raw": float(p), "p_holm": float(q)} for l, p, q in zip(prim_labels, prim_p, adj)]
    if sec_p:
        adj = vc.holm(sec_p)
        R["secondary_family"] = [{"contrast": l, "p_raw": float(p), "p_holm": float(q)} for l, p, q in zip(sec_labels, sec_p, adj)]

    # ---- markdown
    for task in TASKS:
        T = R["tasks"][task]
        lines += [f"## {task}", ""]
        if "A" in T:
            A = T["A"]
            lines += [f"**Arm A** (10 seeds, 300 demos): mean {A['mean']:.3f}, seed SD {A['sd_seed']:.3f} "
                      f"[{A['sd_seed_ci'][0]:.3f}, {A['sd_seed_ci'][1]:.3f}], range {A['min']:.2f}-{A['max']:.2f}",
                      f"Binomial SD of one 50-rollout estimate at this mean: {A['binomial_sd_50_rollouts']:.3f}; "
                      f"seed SD after removing that floor in quadrature: {A['sd_seed_minus_binomial']:.3f} (descriptive only)",
                      "", "seeds 1-10: " + ", ".join(f"{x:.2f}" for x in A["success_rates"]), ""]
        elif "A_partial" in T:
            lines += [f"Arm A partial: {T['A_partial']['n_done']}/10 done", ""]
        for arm in ("B", "C"):
            if arm in T:
                X = T[arm]; m, r = X["mom"], X["reml"]
                lines += [f"**Arm {arm}** 6 x 3 table (rows = {'held-out operator' if arm=='B' else 'random draw'}, cols = seeds 1-3)", "",
                          "| partition | s1 | s2 | s3 | mean |", "|---|---|---|---|---|"]
                for k, row in zip(X["row_keys"], X["table"]):
                    lines.append(f"| {k} | " + " | ".join(f"{v:.2f}" for v in row) + f" | {np.mean(row):.3f} |")
                bp = " (BOUNDARY)" if m["boundary_p"] else ""
                bs = " (BOUNDARY)" if m["boundary_s"] else ""
                rbp = " (BOUNDARY)" if r["boundary_p"] else ""
                rbs = " (BOUNDARY)" if r["boundary_s"] else ""
                lines += ["",
                          f"MoM : SD_partition {m['sd_p']:.3f}{bp}, SD_seed {m['sd_s']:.3f}{bs}, SD_resid {m['sd_e']:.3f}; "
                          f"F-test p(partition) {X['f_test']['p_partition']:.3f}, p(seed) {X['f_test']['p_seed']:.3f}",
                          f"REML: SD_partition {r['sd_p']:.3f}{rbp}, SD_seed {r['sd_s']:.3f}{rbs}, SD_resid {r['sd_e']:.3f}; converged={r['converged']}",
                          f"Estimators disagree materially: partition={X['disagree']['p']}, seed={X['disagree']['s']}", ""]
                if arm == "B":
                    tp, pw = X["tier_permutation"], X["tier_pairwise"]
                    lines += [f"Within-B ratio SD_p/SD_s = {X['within_table_ratio']:.2f}",
                              f"Tier: between-tier share {tp['observed_share']:.2f} (null mean {tp['null_mean_share']:.2f}), exact permutation p = {tp['p_value']:.3f} "
                              f"(floor 1/15 = {tp['min_achievable_p']:.3f}; cannot reject at 0.05 by design, see Amendment 1a); "
                              f"within-tier mean |diff| {pw['within_tier_mean_absdiff']:.3f} vs between-tier {pw['between_tier_mean_absdiff']:.3f}",
                              f"Minimum detectable SD_partition (F-test, alpha 0.05, power 0.8): {X['min_detectable_sd_p_alpha05']:.3f}", ""]
                    if T.get("power_headline_procedure"):
                        lines += ["Power of the preregistered headline procedure (P(interval excludes 1)) at fitted nuisance SDs:", "",
                                  "| true SD_partition | true R | power |", "|---|---|---|"]
                        lines += [f"| {k:.3f} | {v['true_R']:.2f} | {v['power']:.2f} |" for k, v in T["power_headline_procedure"].items()]
                        lines.append("")
        if "headline_ratio_mom" in T:
            h, h2 = T["headline_ratio_mom"], T["headline_ratio_reml"]
            lines += [f"**Headline R = SD_partition(B) / SD_seed(A)**: MoM {h['point']:.2f} [{h['ci_low']:.2f}, {h['ci_high']:.2f}] "
                      f"(one-sided p(R<=1) = {h['p_R_le_1']:.3f}; {h['frac_boundary']*100:.0f}% of resamples at boundary); "
                      f"REML {h2['point']:.2f} [{h2['ci_low']:.2f}, {h2['ci_high']:.2f}]", ""]
        if "B_minus_C" in T:
            d = T["B_minus_C"]
            lines += [f"**B minus C**: D = s2_p(B) - s2_p(C) = {d['point']:.4f} [{d['ci_low']:.4f}, {d['ci_high']:.4f}] "
                      f"(SD_p B {d['sd_p_B']:.3f} vs C {d['sd_p_C']:.3f}; one-sided p(D<=0) = {d['p_D_le_0']:.3f})", ""]
    for fam in ("primary_family", "secondary_family"):
        if fam in R:
            lines += [f"## Holm-Bonferroni: {fam.replace('_', ' ')}", "", "| contrast | p raw | p Holm |", "|---|---|---|"]
            lines += [f"| {e['contrast']} | {e['p_raw']:.4f} | {e['p_holm']:.4f} |" for e in R[fam]]
            lines.append("")
    lines += ["", "Zero variance estimates marked BOUNDARY are boundary estimates, not evidence of zero variance."]

    os.makedirs(os.path.join(REPO, "results"), exist_ok=True)
    with open(os.path.join(REPO, "results", "analysis.json"), "w") as fh:
        json.dump(R, fh, indent=1, default=lambda o: None)
    with open(os.path.join(REPO, "results", "analysis_summary.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
